### ISSUE TITLE
[chore] Staging area for open PRs

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/OCM-API#48] opened 2021-05-13 10:27 UTC
https://cs3org.github.io/OCM-API/ builds from the 'develop' branch.
How can we view a ReDoc build from a different branch, so that we can see what the effect of merging a PR would be?

**Comment by glpatcern** [comment] 2023-02-19 14:04
Duplicate of #44

**Closed as completed by glpatcern** 2023-02-19 14:04 UTC
